# Generated by Django 2.1.7 on 2019-08-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginModule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='emailId',
        ),
        migrations.RemoveField(
            model_name='user',
            name='userId',
        ),
        migrations.AddField(
            model_name='profile',
            name='phoneNo',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='user',
            name='emailId',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
