# Generated by Django 2.1.7 on 2019-08-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginModule', '0002_auto_20190823_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profileUser',
        ),
        migrations.AddField(
            model_name='user',
            name='phoneNo',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='user',
            name='userName',
            field=models.CharField(default='USER', max_length=50),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
